const mockConversas = [
  {
    conversaId: "conv_123456789",
    cliente: {
      nome: "Maria Silva",
      numero: "+5511999999999",
      avatar: "https://ui-avatars.com/api/?name=Maria+Silva",
    },
    atendente: {
      nome: "Suporte Ana",
      numero: "suporte@empresa.com", // ou ID interno
    },
    status: "aguardando_resposta",
    prioridade: "alta",
    etiquetas: ["urgente", "dúvida técnica"],
    canal: "whatsapp",
    criadoEm: "2025-04-05T08:10:00Z",
    ultimaAtualizacao: "2025-04-05T08:35:00Z",
    mensagens: [
      {
        id: "msg_001",
        from: "cliente", // ou "atendente"
        mensagem: "Olá, estou com problema no login do app.",
        sentAt: "2025-04-05T08:10:00Z",
        updatedAt: "2025-04-05T08:10:00Z",
        lida: true,
      },
      {
        id: "msg_002",
        from: "atendente",
        mensagem: "Olá Maria! Pode me dizer qual erro aparece na tela?",
        sentAt: "2025-04-05T08:35:00Z",
        updatedAt: "2025-04-05T08:35:00Z",
        lida: true,
      },
      {
        id: "msg_003",
        from: "cliente",
        mensagem:
          "Aparece 'credenciais inválidas', mas eu tenho certeza que está certo.",
        sentAt: "2025-04-05T08:37:00Z",
        updatedAt: "2025-04-05T08:37:00Z",
        lida: false,
      },
    ],
  },
  {
    conversaId: "conv_987654321",
    cliente: {
      nome: "João Pedro",
      numero: "+5511888888888",
      avatar: "https://ui-avatars.com/api/?name=João+Pedro",
    },
    atendente: null, // ainda não atribuído
    status: "nova",
    prioridade: "normal",
    etiquetas: ["orçamento"],
    canal: "whatsapp",
    criadoEm: "2025-04-05T09:15:00Z",
    ultimaAtualizacao: "2025-04-05T09:15:00Z",
    mensagens: [
      {
        id: "msg_101",
        from: "cliente",
        mensagem: "Bom dia! Vocês fazem instalação de ar condicionado?",
        sentAt: "2025-04-05T09:15:00Z",
        updatedAt: "2025-04-05T09:15:00Z",
        lida: false,
      },
    ],
  },
];

const integrationMessage = {
  ticket: {
    id: 167715,
    status: "closed",
    unreadMessages: 0,
    lastMessage: "A conversa foi transferida para o atendente Caio Simões! ",
    firstMessage: "*Caio Simões*:\nOi",
    channel: "whatsapp",
    answered: true,
    isGroup: false,
    isActiveDemand: true,
    isCreatedAPI: false,
    lastInteractionBot: null,
    lastOutOfHoursMessage: null,
    lastOutOfAbsenseMessage: null,
    origem: "C",
    botRetries: 0,
    closedAt: "1764243246523",
    lastMessageAt: "1764242486707",
    startedAttendanceAt: null,
    userId: 377,
    contactId: 147534,
    whatsappId: 135,
    promptId: null,
    autoReplyId: null,
    stepAutoReplyId: null,
    chatFlowId: null,
    stepChatFlow: null,
    queueId: 215,
    closingReasonId: 207,
    tenantId: 75,
    isCreatedPush: false,
    apiConfig: null,
    variables: {},
    externalKey: null,
    isFixed: false,
    contactFunnelId: null,
    unread: false,
    timestamp: null,
    slaTime: null,
    saleValue: null,
    sentiment: null,
    sentimentNote: null,
    createdAt: "2025-11-27T11:13:36.148Z",
    updatedAt: "2025-11-27T11:34:06.523Z",
    contact: {
      id: 147534,
      name: "Caio",
      number: "558185053082",
      lid: "172327123869878",
      isNumber: true,
      email: "",
      profilePicUrl: null,
      pushname: "558185053082",
      observations: null,
      channel: "whatsapp",
      isUser: true,
      isWAContact: true,
      isGroup: false,
      deletedAt: null,
      negotiatedValue: null,
      leadStatusId: null,
      leadOriginId: null,
      queueId: null,
      tenantId: 75,
      customFields: {},
      tags: [],
      firstConnection: 135,
      createdAt: "2025-11-27T11:13:36.137Z",
      updatedAt: "2025-11-27T11:13:53.029Z",
      extraInfo: [],
      leadStatus: null,
      leadOrigin: null,
      wallets: [],
      firstConnectionModel: {
        UrlWabaWebHook:
          "https://enterprise-217api.rmchat.com.br/wabahooks/null/null",
        UrlMessengerWebHook:
          "https://enterprise-217api.rmchat.com.br/fb-messenger-hooks/null",
        id: 135,
        name: "Suporte",
        session: null,
        qrcode: "",
        status: "CONNECTED",
        battery: null,
        plugged: null,
        isActive: true,
        enableSentimentAnalysis: true,
        disableBotAfterAbsence: false,
        refuseComments: false,
        isRejectCall: false,
        callRejectedMessage: null,
        isDeleted: false,
        retries: 0,
        pid: null,
        isDefault: true,
        monitoring: true,
        archiveChat: false,
        isSyncOldMessages: false,
        remoteAuth: false,
        tokenTelegram: null,
        instagramUser: null,
        instagramKey: null,
        fbPageId: null,
        phoneId: null,
        fbObject: null,
        url: "https://wa-16-go.clickmassa.com.br",
        container: "wa-16-go",
        type: "whatsapp",
        restartAt: null,
        number: "558196091011",
        minutesInactivity: 0,
        phone: null,
        balance: null,
        tenantId: 75,
        wabaBSP: null,
        commentTab: "all",
        provider: "baileys",
        tokenAPI: null,
        uid: "db8d1e2f-13ab-4416-b340-46ea36e81108",
        tokenHook: null,
        originalType: null,
        editedAt: null,
        businessHours: [
          {
            day: 0,
            hr1: "08:00",
            hr2: "12:00",
            hr3: "14:00",
            hr4: "18:00",
            type: "O",
            label: "Domingo",
          },
          {
            day: 1,
            hr1: "08:00",
            hr2: "12:00",
            hr3: "14:00",
            hr4: "18:00",
            type: "O",
            label: "Segunda-Feira",
          },
          {
            day: 2,
            hr1: "08:00",
            hr2: "12:00",
            hr3: "14:00",
            hr4: "18:00",
            type: "O",
            label: "Terça-Feira",
          },
          {
            day: 3,
            hr1: "08:00",
            hr2: "12:00",
            hr3: "14:00",
            hr4: "18:00",
            type: "O",
            label: "Quarta-Feira",
          },
          {
            day: 4,
            hr1: "08:00",
            hr2: "12:00",
            hr3: "14:00",
            hr4: "18:00",
            type: "O",
            label: "Quinta-Feira",
          },
          {
            day: 5,
            hr1: "08:00",
            hr2: "12:00",
            hr3: "14:00",
            hr4: "18:00",
            type: "O",
            label: "Sexta-Feira",
          },
          {
            day: 6,
            hr1: "08:00",
            hr2: "12:00",
            hr3: "14:00",
            hr4: "18:00",
            type: "O",
            label: "Sábado",
          },
        ],
        messageBusinessHours: null,
        enableActiveSearchControl: false,
        tokenWaVoip: null,
        activeSearchLimit: 30,
        currentAmountOfActiveSearch: 0,
        createdAt: "2025-11-27T11:05:34.952Z",
        updatedAt: "2025-11-27T11:11:58.975Z",
        chatFlowId: null,
        inactivityClosingReasonId: null,
        defaultQueueId: null,
        promptId: null,
      },
    },
    user: {
      id: 377,
      name: "Caio Simões",
      email: "caio@futuratec.srv.br",
    },
    whatsapp: {
      id: 135,
      name: "Suporte",
      type: "whatsapp",
      originalType: null,
      editedAt: null,
      tokenWaVoip: null,
      wabaBSP: null,
    },
    queue: {
      id: 215,
      queue: "Suporte - Websites",
      isActive: true,
      userId: 377,
      tenantId: 75,
      messageDefaultContact: null,
      createdAt: "2025-11-27T11:05:33.249Z",
      updatedAt: "2025-11-27T11:05:33.249Z",
    },
    messages: [
      {
        mediaName: null,
        mediaUrl: "",
        msgCreatedAt: null,
        id: "34e1b811-c357-4a62-8cac-3441a81a0fab",
        messageId: "44556964D07A34C852F1",
        ack: 3,
        status: "sended",
        wabaMediaId: null,
        read: true,
        fromMe: true,
        body: "Seja bem-vindo(a)!\n\n⚠️ *Digite o número de uma opção:*\n\n*1* - Suporte - Sistemas OnyxErp\n*2* - Suporte - Sistema FOPAG\n*3* - Suporte - Assessoria Técnica\n*4* - Suporte - Assessoria Benefício\n*5* - Suporte - eSocial\n*6* - FlowDocs\n*7* - Atuária\n*8* - Suporte - Websites\n*0* - Finalizar conversa\n\nℹ️ *Fique tranquilo! As informações coletadas neste atendimento são utilizadas apenas para fins autorizados e em total conformidade com a LGPD.*",
        caption: null,
        originalName: null,
        size: 0,
        previousBody: null,
        mediaType: "text",
        isDeleted: false,
        createdAt: "2025-11-27T11:13:56.421Z",
        updatedAt: "2025-11-27T11:13:56.526Z",
        quotedMsgId: null,
        ticketId: 167715,
        contactId: 147534,
        timestamp: "1764242036526",
        userId: null,
        scheduleDate: null,
        sendType: null,
        tenantId: 75,
        tenantUid: "571b90e5-4c7f-4da5-98d9-4ec8875d3a82",
        note: false,
        isObjectStorage: true,
        importStatus: null,
        isTransfer: false,
        externalKey: null,
      },
      {
        mediaName: null,
        mediaUrl: "",
        msgCreatedAt: null,
        id: "bfefd7e1-02c2-4c01-b47c-171d2c562a84",
        messageId: "3EB03211F87B28A96201BF",
        ack: 3,
        status: "sended",
        wabaMediaId: null,
        read: true,
        fromMe: true,
        body: "*Caio Simões*:\nOi",
        caption: null,
        originalName: null,
        size: 0,
        previousBody: null,
        mediaType: "chat",
        isDeleted: false,
        createdAt: "2025-11-27T11:13:36.168Z",
        updatedAt: "2025-11-27T11:13:41.803Z",
        quotedMsgId: null,
        ticketId: 167715,
        contactId: 147534,
        timestamp: "1764242021803",
        userId: 377,
        scheduleDate: null,
        sendType: "chat",
        tenantId: 75,
        tenantUid: "571b90e5-4c7f-4da5-98d9-4ec8875d3a82",
        note: false,
        isObjectStorage: true,
        importStatus: null,
        isTransfer: false,
        externalKey: null,
      },
      {
        mediaName: null,
        mediaUrl: "",
        msgCreatedAt: null,
        id: "8451e9b3-77c0-4567-abd1-77b65db939b7",
        messageId: "AC7B136B379131F0310581B068BA9731",
        ack: 0,
        status: "received",
        wabaMediaId: null,
        read: true,
        fromMe: false,
        body: "oi, tudo bem?",
        caption: null,
        originalName: null,
        size: 0,
        previousBody: null,
        mediaType: "text",
        isDeleted: false,
        createdAt: "2025-11-27T11:13:53.063Z",
        updatedAt: "2025-11-27T11:22:18.196Z",
        quotedMsgId: null,
        ticketId: 167715,
        contactId: 147534,
        timestamp: "1764242032000",
        userId: null,
        scheduleDate: null,
        sendType: null,
        tenantId: 75,
        tenantUid: "571b90e5-4c7f-4da5-98d9-4ec8875d3a82",
        note: false,
        isObjectStorage: true,
        importStatus: null,
        isTransfer: false,
        externalKey: null,
      },
      {
        mediaName: null,
        mediaUrl: "",
        msgCreatedAt: null,
        id: "e7f87fc0-6dcc-4561-8484-57c2fc93096e",
        messageId: "3EB058F4D1F071CA75F307",
        ack: 3,
        status: "sended",
        wabaMediaId: null,
        read: true,
        fromMe: true,
        body: "Sua conversa foi transferida para o departamento Suporte - Sistemas OnyxErp! ",
        caption: null,
        originalName: null,
        size: 0,
        previousBody: null,
        mediaType: "text",
        isDeleted: false,
        createdAt: "2025-11-27T11:21:26.477Z",
        updatedAt: "2025-11-27T11:21:26.519Z",
        quotedMsgId: null,
        ticketId: 167715,
        contactId: 147534,
        timestamp: "1764242486519",
        userId: null,
        scheduleDate: null,
        sendType: null,
        tenantId: 75,
        tenantUid: "571b90e5-4c7f-4da5-98d9-4ec8875d3a82",
        note: false,
        isObjectStorage: true,
        importStatus: null,
        isTransfer: false,
        externalKey: null,
      },
      {
        mediaName: null,
        mediaUrl: "",
        msgCreatedAt: null,
        id: "3a3d4268-b657-450c-8000-1ecc941e3010",
        messageId: "3EB076016A163020A21741",
        ack: 3,
        status: "sended",
        wabaMediaId: null,
        read: true,
        fromMe: true,
        body: "A conversa foi transferida para o atendente Caio Simões! ",
        caption: null,
        originalName: null,
        size: 0,
        previousBody: null,
        mediaType: "text",
        isDeleted: false,
        createdAt: "2025-11-27T11:21:26.669Z",
        updatedAt: "2025-11-27T11:21:26.693Z",
        quotedMsgId: null,
        ticketId: 167715,
        contactId: 147534,
        timestamp: "1764242486693",
        userId: null,
        scheduleDate: null,
        sendType: null,
        tenantId: 75,
        tenantUid: "571b90e5-4c7f-4da5-98d9-4ec8875d3a82",
        note: false,
        isObjectStorage: true,
        importStatus: null,
        isTransfer: false,
        externalKey: null,
      },
    ],
  },
  tenantId: 75,
  config: {
    id: "36ddf48b-95fd-45e8-8e1b-38ddba306811",
    sessionId: 135,
    name: "Integração Cange",
    isActive: true,
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRJZCI6NzUsInByb2ZpbGUiOiJhZG1pbiIsInNlc3Npb25JZCI6MTM1LCJjaGFubmVsVHlwZSI6IndoYXRzYXBwIiwiaWF0IjoxNzY0MjQxOTc5LCJleHAiOjE4MjczMTM5Nzl9.XfAS3yTsomTouk638-J1N9sr2Oh4lsEs8sghU_uteSI",
    authToken: null,
    urlServiceStatus: null,
    urlMessageStatus: null,
    ticketAction: "OT",
    queueId: null,
    userId: 377,
    createdAt: "2025-11-27T11:12:59.780Z",
    updatedAt: "2025-11-27T11:12:59.780Z",
    tenantId: 75,
    isNewTicket: false,
    isFinishedTicket: false,
    isFinishedTicketHistoricMessages: true,
    isStartedTicket: false,
    isUpdateOnTicket: false,
    isTransferOfTicket: false,
    isNewMessage: false,
    isAckMessage: false,
    isNewContact: false,
    isUpdateContact: false,
    isConnectionStatusUpdate: false,
    isOpportunity: false,
    webhookUrl: "https://cange-bash-integra.vercel.app/api/webhook/messages",
  },
  event: "FinishedTicketHistoricMessages",
};

export default mockConversas;
